/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DocumentValue } from './documentValue';

export class CreateDocumentRequest {
    /**
    * The user ID the document is for.
    */
    'recipientId': string;
    /**
    * Key-value pairs to be used in the document.
    */
    'documentValues': Array<DocumentValue>;
    /**
    * Amount of days the document will be valid for since the date of its creation. Only required if template type is Lease.
    */
    'expiresIn'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recipientId",
            "baseName": "recipientId",
            "type": "string"
        },
        {
            "name": "documentValues",
            "baseName": "documentValues",
            "type": "Array<DocumentValue>"
        },
        {
            "name": "expiresIn",
            "baseName": "expiresIn",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateDocumentRequest.attributeTypeMap;
    }
}

