/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateDocumentSignatureRequest {
    /**
    * The id of the person who has signed.
    */
    'signeeId': string;
    /**
    * The type of signee; 1 = user, 2 = contact
    */
    'signeeType'?: number;
    /**
    * The ID of the field that has been signed.
    */
    'signatureFieldId': string;
    /**
    * The ID of the date field that has been signed.
    */
    'signatureDateFieldId': string;
    /**
    * Canvas Data URL
    */
    'signatureData': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "signeeId",
            "baseName": "signeeId",
            "type": "string"
        },
        {
            "name": "signeeType",
            "baseName": "signeeType",
            "type": "number"
        },
        {
            "name": "signatureFieldId",
            "baseName": "signatureFieldId",
            "type": "string"
        },
        {
            "name": "signatureDateFieldId",
            "baseName": "signatureDateFieldId",
            "type": "string"
        },
        {
            "name": "signatureData",
            "baseName": "signatureData",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateDocumentSignatureRequest.attributeTypeMap;
    }
}

