/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateTemplateRequest {
    /**
    * Name of your template
    */
    'templateName': string;
    /**
    * Description of your template
    */
    'templateDescription': string;
    /**
    * Encoded HTML
    */
    'markup': string;
    /**
    * The template type. -  1 = lease, 2 = confirmation, 3 = information, 4 = insurance
    */
    'templateTypeId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "templateName",
            "baseName": "templateName",
            "type": "string"
        },
        {
            "name": "templateDescription",
            "baseName": "templateDescription",
            "type": "string"
        },
        {
            "name": "markup",
            "baseName": "markup",
            "type": "string"
        },
        {
            "name": "templateTypeId",
            "baseName": "templateTypeId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateTemplateRequest.attributeTypeMap;
    }
}

