/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DocumentSignatureResponse {
    /**
    * Document signature Id
    */
    'documentSignatureId': string;
    /**
    * The id of the person who has signed.
    */
    'signeeId': string;
    /**
    * The type of signee; 1 = user, 2 = contact
    */
    'signeeType'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "documentSignatureId",
            "baseName": "documentSignatureId",
            "type": "string"
        },
        {
            "name": "signeeId",
            "baseName": "signeeId",
            "type": "string"
        },
        {
            "name": "signeeType",
            "baseName": "signeeType",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DocumentSignatureResponse.attributeTypeMap;
    }
}

