/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TemplateResponse {
    /**
    * Template Id
    */
    'templateId': string;
    /**
    * Template Name
    */
    'templateName': string;
    /**
    * Template Description
    */
    'templateDescription': string;
    /**
    * Id of the template
    */
    'templateVersionId': string;
    /**
    * The Version of the template.
    */
    'templateVersion': number;
    /**
    * Encoded HTML
    */
    'markup': string;
    /**
    * Template type.
    */
    'templateTypeId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "templateId",
            "baseName": "templateId",
            "type": "string"
        },
        {
            "name": "templateName",
            "baseName": "templateName",
            "type": "string"
        },
        {
            "name": "templateDescription",
            "baseName": "templateDescription",
            "type": "string"
        },
        {
            "name": "templateVersionId",
            "baseName": "templateVersionId",
            "type": "string"
        },
        {
            "name": "templateVersion",
            "baseName": "templateVersion",
            "type": "number"
        },
        {
            "name": "markup",
            "baseName": "markup",
            "type": "string"
        },
        {
            "name": "templateTypeId",
            "baseName": "templateTypeId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TemplateResponse.attributeTypeMap;
    }
}

